services:
  mockserver:
    image: mockserver/mockserver:5.12.0
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/init_mockserver.json
    volumes:
      - ./init_mockserver.json:/config/init_mockserver.json